import { Group, Team, Match, KnockoutMatch } from "./types";

export const GROUPS: Record<string, Group> = {
  A: {
    name: "A",
    teams: [
      { name: "México", flag: "🇲🇽", played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 0 },
      { name: "África do Sul", flag: "🇿🇦", played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 0 },
      { name: "Coreia do Sul", flag: "🇰🇷", played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 0 },
      { name: "República Tcheca", flag: "🇨🇿", played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 0 },
    ],
    matches: [
      {
        id: "A1",
        homeTeam: "México",
        awayTeam: "África do Sul",
        homeTeamFlag: "🇲🇽",
        awayTeamFlag: "🇿🇦",
        date: new Date("2026-06-11T18:00:00Z"),
        group: "A",
        status: "pending",
        phase: "groups",
      },
      {
        id: "A2",
        homeTeam: "Coreia do Sul",
        awayTeam: "República Tcheca",
        homeTeamFlag: "🇰🇷",
        awayTeamFlag: "🇨🇿",
        date: new Date("2026-06-11T21:00:00Z"),
        group: "A",
        status: "pending",
        phase: "groups",
      },
      {
        id: "A3",
        homeTeam: "República Tcheca",
        awayTeam: "África do Sul",
        homeTeamFlag: "🇨🇿",
        awayTeamFlag: "🇿🇦",
        date: new Date("2026-06-18T18:00:00Z"),
        group: "A",
        status: "pending",
        phase: "groups",
      },
      {
        id: "A4",
        homeTeam: "México",
        awayTeam: "Coreia do Sul",
        homeTeamFlag: "🇲🇽",
        awayTeamFlag: "🇰🇷",
        date: new Date("2026-06-24T21:00:00Z"),
        group: "A",
        status: "pending",
        phase: "groups",
      },
      {
        id: "A5",
        homeTeam: "México",
        awayTeam: "República Tcheca",
        homeTeamFlag: "🇲🇽",
        awayTeamFlag: "🇨🇿",
        date: new Date("2026-06-24T21:00:00Z"),
        group: "A",
        status: "pending",
        phase: "groups",
      },
      {
        id: "A6",
        homeTeam: "África do Sul",
        awayTeam: "Coreia do Sul",
        homeTeamFlag: "🇿🇦",
        awayTeamFlag: "🇰🇷",
        date: new Date("2026-06-24T21:00:00Z"),
        group: "A",
        status: "pending",
        phase: "groups",
      },
    ],
  },
  B: {
    name: "B",
    teams: [
      { name: "Canadá", flag: "🇨🇦", played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 0 },
      { name: "Bósnia e Herzegovina", flag: "🇧🇦", played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 0 },
      { name: "Suíça", flag: "🇨🇭", played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 0 },
      { name: "Catar", flag: "🇶🇦", played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 0 },
    ],
    matches: [
      {
        id: "B1",
        homeTeam: "Canadá",
        awayTeam: "Bósnia e Herzegovina",
        homeTeamFlag: "🇨🇦",
        awayTeamFlag: "🇧🇦",
        date: new Date("2026-06-12T18:00:00Z"),
        group: "B",
        status: "pending",
        phase: "groups",
      },
      {
        id: "B2",
        homeTeam: "Suíça",
        awayTeam: "Catar",
        homeTeamFlag: "🇨🇭",
        awayTeamFlag: "🇶🇦",
        date: new Date("2026-06-12T21:00:00Z"),
        group: "B",
        status: "pending",
        phase: "groups",
      },
      {
        id: "B3",
        homeTeam: "Suíça",
        awayTeam: "Bósnia e Herzegovina",
        homeTeamFlag: "🇨🇭",
        awayTeamFlag: "🇧🇦",
        date: new Date("2026-06-19T18:00:00Z"),
        group: "B",
        status: "pending",
        phase: "groups",
      },
      {
        id: "B4",
        homeTeam: "Canadá",
        awayTeam: "Catar",
        homeTeamFlag: "🇨🇦",
        awayTeamFlag: "🇶🇦",
        date: new Date("2026-06-24T18:00:00Z"),
        group: "B",
        status: "pending",
        phase: "groups",
      },
      {
        id: "B5",
        homeTeam: "Bósnia e Herzegovina",
        awayTeam: "Catar",
        homeTeamFlag: "🇧🇦",
        awayTeamFlag: "🇶🇦",
        date: new Date("2026-06-24T18:00:00Z"),
        group: "B",
        status: "pending",
        phase: "groups",
      },
      {
        id: "B6",
        homeTeam: "Canadá",
        awayTeam: "Suíça",
        homeTeamFlag: "🇨🇦",
        awayTeamFlag: "🇨🇭",
        date: new Date("2026-06-24T18:00:00Z"),
        group: "B",
        status: "pending",
        phase: "groups",
      },
    ],
  },
  C: {
    name: "C",
    teams: [
      { name: "Brasil", flag: "🇧🇷", played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 0 },
      { name: "Marrocos", flag: "🇲🇦", played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 0 },
      { name: "Escócia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 0 },
      { name: "Haiti", flag: "🇭🇹", played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 0 },
    ],
    matches: [
      {
        id: "C1",
        homeTeam: "Brasil",
        awayTeam: "Marrocos",
        homeTeamFlag: "🇧🇷",
        awayTeamFlag: "🇲🇦",
        date: new Date("2026-06-13T18:00:00Z"),
        group: "C",
        status: "pending",
        phase: "groups",
      },
      {
        id: "C2",
        homeTeam: "Escócia",
        awayTeam: "Haiti",
        homeTeamFlag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        awayTeamFlag: "🇭🇹",
        date: new Date("2026-06-13T21:00:00Z"),
        group: "C",
        status: "pending",
        phase: "groups",
      },
      {
        id: "C3",
        homeTeam: "Brasil",
        awayTeam: "Haiti",
        homeTeamFlag: "🇧🇷",
        awayTeamFlag: "🇭🇹",
        date: new Date("2026-06-19T21:00:00Z"),
        group: "C",
        status: "pending",
        phase: "groups",
      },
      {
        id: "C4",
        homeTeam: "Escócia",
        awayTeam: "Marrocos",
        homeTeamFlag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        awayTeamFlag: "🇲🇦",
        date: new Date("2026-06-19T18:00:00Z"),
        group: "C",
        status: "pending",
        phase: "groups",
      },
      {
        id: "C5",
        homeTeam: "Brasil",
        awayTeam: "Escócia",
        homeTeamFlag: "🇧🇷",
        awayTeamFlag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        date: new Date("2026-06-24T21:00:00Z"),
        group: "C",
        status: "pending",
        phase: "groups",
      },
      {
        id: "C6",
        homeTeam: "Marrocos",
        awayTeam: "Haiti",
        homeTeamFlag: "🇲🇦",
        awayTeamFlag: "🇭🇹",
        date: new Date("2026-06-24T21:00:00Z"),
        group: "C",
        status: "pending",
        phase: "groups",
      },
    ],
  },
};

// Knockout bracket structure (32 teams, 8 best third-place teams)
export const KNOCKOUT_BRACKET: Record<string, KnockoutMatch[]> = {
  round32: Array.from({ length: 16 }, (_, i) => ({
    id: `R32_${i + 1}`,
    round: "round32" as const,
    matchNumber: i + 1,
    status: "pending" as const,
  })),
  round16: Array.from({ length: 8 }, (_, i) => ({
    id: `R16_${i + 1}`,
    round: "round16" as const,
    matchNumber: i + 1,
    status: "pending" as const,
  })),
  quarterfinal: Array.from({ length: 4 }, (_, i) => ({
    id: `QF_${i + 1}`,
    round: "quarterfinal" as const,
    matchNumber: i + 1,
    status: "pending" as const,
  })),
  semifinal: Array.from({ length: 2 }, (_, i) => ({
    id: `SF_${i + 1}`,
    round: "semifinal" as const,
    matchNumber: i + 1,
    status: "pending" as const,
  })),
  final: [
    {
      id: "FINAL",
      round: "final" as const,
      matchNumber: 1,
      status: "pending" as const,
    },
  ],
};

// Sistema de pontuação
export const SCORING_SYSTEM = {
  EXACT_RESULT: 10, // Acerto exato do placar (ex: 2-1)
  CORRECT_WINNER: 5, // Acerto do vencedor mas placar errado
  CORRECT_DRAW: 5, // Acerto de empate mas gols errados
  KNOCKOUT_WINNER: 10, // Acerto do vencedor no mata-mata
};
